### ISSUE TITLE
hotspot is having issue in kali linux(Rolling)

### ISSUE THREAD

**Issue by tycoon420** [prahladyeri/hotspotd#28] opened 2016-02-21 19:38 UTC
Was using hotspotd in Kali (Sana) without any trouble but after updating Kali to Rolling. hotspotd is not working properly. hotspot is created n its showing on the phone but when i connect to hotspotd internet cannot be accessed.Plus when i want to stop hotspotd, the command works n it shows hotspot has stopped, but still i can see the hotspot in my phone :/
help me bro.
![screenshot from 2016-02-22 01-06-10](https://cloud.githubusercontent.com/assets/11652113/13204868/974f218c-d900-11e5-8bdd-6bd839e297b0.png)
![screenshot from 2016-02-22 01-07-53](https://cloud.githubusercontent.com/assets/11652113/13204873/c856edb4-d900-11e5-943a-86f3a9316447.png)

**Comment by prahladyeri** [comment] 2016-02-21 20:19
> hotspot is created n its showing on the phone but when i connect to hotspotd internet cannot be accessed.

Most probably, it seems to be an issue with iptables. Perhaps your new version of Kali is changing `iptables` internally so the hotspotd isn't able to mangle it. What is the output of `iptables -L` (in root)?
Also, what version of hotspotd are you using in the first place?

**Comment by tycoon420** [comment] 2016-02-21 20:51
m using hotspotd 0.1.5 
n here is the screenshot of iptables -L
![screenshot from 2016-02-22 02-19-36](https://cloud.githubusercontent.com/assets/11652113/13205275/f18e8ebc-d90a-11e5-888d-d51ec7e458c5.png)

**Comment by prahladyeri** [comment] 2016-02-21 21:35
If you are able to access internet on this machine, it may be an issue on the handset side. Did you check with multiple handsets/devices?

**Comment by tycoon420** [comment] 2016-02-21 21:44
i tried connecting to the hotspot with 3 devices n still cant browse internet.

**Comment by prahladyeri** [comment] 2016-02-21 21:59
From hotspotd output, the connection is made between `wlan0<->eth0`. Are you sure `eth0` is the interface that is used to access the internet? If not, then do an `ifconfig` to verify which interface are you using for browsing the internet. If it has changed, then run hotspotd with `configure` argument once to re-configure it.

**Comment by tycoon420** [comment] 2016-02-21 22:04
i am using ethernet to access  internet.
here is Screenshot of ifconfig. 
![screenshot from 2016-02-22 03-31-54](https://cloud.githubusercontent.com/assets/11652113/13205742/190fe436-d915-11e5-909f-19efec8e7571.png)

**Comment by prahladyeri** [comment] 2016-02-21 22:24
In that case, there could  be multiple issues, try this way:

1. Run `rfkill list` and make sure that wifi radio is not hard-blocked on your machine. If this command doesn't work, its even more problematic as hotspotd daemon uses rkfill internally to work.

2. If rfkill/hardblock isn't the issue, then install the latest 0.1.6 version. I've added a few more debug messages that might help us trouble shoot the issue. Start hotspotd with this new version and let me know the output.

3. If both the above points don't work, we may have to do a step by step debug. The daemon first starts dnsmasq for dhcp provisioning and then starts the hostapd. So, you will have to stop the hotspotd and run dnsmasq manually like this and see what errors it is giving:

    dnsmasq --dhcp-authoritative --interface=wlan0 --dhcp-range=192.168.45.20,192.168.45.100,255.255.255.0,4h

**Comment by tycoon420** [comment] 2016-02-21 22:40
rfkill list command works well n the output is attached below
![screenshot from 2016-02-22 03-56-55](https://cloud.githubusercontent.com/assets/11652113/13205934/c2fa80ce-d919-11e5-9a96-596e06231595.png)
i installed the new hotspotd 0.1.6v but same thing is happening. not able to access the internet on my both phones.

i didnt understand the 3rd point which u mentioned.Could u plz elaborate more precisely. sorry but m new to Linux.

**Comment by prahladyeri** [comment] 2016-02-21 22:50
> i installed the new hotspotd 0.1.6v but same thing is happening.

Even if same thing is happening, lets see its output after running it? I've added some additional things like the complete `dnsmasq` command and the `hostapd` parameters.

> i didnt understand the 3rd point which u mentioned.Could u plz elaborate more precisely. 

Well, debugging is a step-by-step procedure to find out where exactly the issue is in a complex program. But don't worry about that, after running the new version, just paste whatever output the script is giving and we will see from there.

**Comment by tycoon420** [comment] 2016-02-21 22:54
here is the final output after running hotspotd 0.1.6
![screenshot from 2016-02-22 04-23-36](https://cloud.githubusercontent.com/assets/11652113/13206043/253d3176-d91c-11e5-83a8-ab5c47746c75.png)

**Comment by prahladyeri** [comment] 2016-02-21 23:02
k. Firstly, copy these two commands from the above console output and keep them in your text editor (they are second/third lines from the end):

`dnsmasq --dhcp-authoritative --interface=wlan0......`
`hostapd -B /usr/local/lib/python2.7......`

After that, Stop hotspotd first by running `hotspotd stop` and then run the above commands one by one, then state their output.

**Comment by tycoon420** [comment] 2016-02-21 23:08
Bro here is the output of both the commands.
![screenshot from 2016-02-22 04-37-18](https://cloud.githubusercontent.com/assets/11652113/13206124/1e72179c-d91e-11e5-99b5-ac1bdc416634.png)

**Comment by prahladyeri** [comment] 2016-02-21 23:15
Carefully run the below commands in su mode one by one and tell me which one of them works:

    nmcli nm wifi off
    nmcli radio wifi off

**Comment by tycoon420** [comment] 2016-02-21 23:19
nmcli nm wifi off - not working 
it gives error- Error: Object 'nm' is unknown, try 'nmcli help'.

nmcli radio wifi off -this one is working.

**Comment by prahladyeri** [comment] 2016-02-21 23:30
Well, I initially thought that inconsistency in `nmcli` command might be causing problem in your case, but turns out I've already fixed that before v0.1.5. In your case, there seems to be something hardware specific. If it was working earlier, then the newer Kali update might have introduced something that is causing this. One thing you can try is to stop the network-manager service in this manner before starting hotspotd:

service network-manager stop

This might help if the GNOME network manager is interfering with hotspotd. Other than that, I'm at a loss. Maybe these links might help you if you study them in detail:

http://nims11.wordpress.com/2012/04/27/hostapd-the-linux-way-to-create-virtual-wifi-access-point/comment-page-5/
http://askubuntu.com/questions/319838/failed-to-set-interface-wlan0-into-ap-mode-intel-centrino-n1000-wireless
http://askubuntu.com/questions/472794/hostapd-error-nl80211-could-not-configure-driver-mode

**Comment by tycoon420** [comment] 2016-02-21 23:42
No prob bro u tried ur best and Thanks a lot for ur time n ur work  . N yeah it was working like a charm in Kali Sana 2.0. Will try later, its 5am n got college from 9 am. keep up the good work n ur knowledge is immense would like to learn from u. thanks anyways. (Y).

**Comment by prahladyeri** [comment] 2016-02-21 23:50
No probs. The trick of fixing things in linux is just to stick to it. It might take a hundred more attempts, but if you learn it this way, the learning will be ingrained in you and make you a better developer. If you just perform `apt-get install <package>`, it might work, but you will never know how the stack works at the lower levels. Anyways, all the best for your studies.

**Comment by beflo** [comment] 2016-03-21 18:24
Any development on this issue?

**Comment by RRibbon** [comment] 2017-10-04 02:29
hi everyone..

i had a issues when i start hotspotd

im already configure ip address,passwrd,also ssid,everything is fine..

i connected with the hotspot,

and here's the problem

1.when hotspotd turn on,my pc automatically turn of wifi connection,so my phone cannot connect to the internet because of that.

2.what shoud i do?
if anyone could help me,what should i tell to you,maybe i should check something to clear this problem?

btw im newbie,thanks-

**Comment by prahladyeri** [comment] 2019-07-04 07:21
Closing as there has been no activity.

**Closed by prahladyeri** 2019-07-04 07:21 UTC
Labels: help wanted

**Comment by sudesh1122** [comment] 2019-07-22 12:35
I had set up the hotspot and other devices are showing this Pac's name after wifi network searching but even a single device is not able to connect to this network. Btw I'm using Kali Linux. Please help.....
